### PR TITLE
README.md: Add ELF debugging instructions

### PR DESCRIPTION
**Pull request by mkroening**
See https://github.com/unikraft/run-app-elfloader/pull/3.

### CODE REVIEW

File: README.md [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+    Here, the start address is `0x3fe01000`.
+
+4. Explicitly add the debug symbols from the ELF app:
+
+    ```
+    add-symbol-file filename -o offset
+    ```
+
+Common symbols like `main` might exist in both the KVM image and the ELF application.
+You can be specific by referring to their respective source file: `helloworld.c:main` instead of just `main`.
```
Comment (razvand) [inline README.md]: I would mention the use the `info functions regexp` feature in [GDB](https://sourceware.org/gdb/onlinedocs/gdb/Symbols.html). Such that, for example, you would use `info function ^main$` to print out where the main function is located.

File: README.md [hunk 2]
```diff
@@ -0,0 +1,28 @@
+# app-elfloader
```
Comment (razvand) [inline README.md]: Add a short description about the ELF loader app.

File: README.md (hunk 1 above)
Comment (mkroening) [reply README.md]: Done :+1:

File: README.md (hunk 2 above)
Comment (mkroening) [reply README.md]: I added a sentence and a reference to the Run App ELF loader repo, which is more elaborate to avoid duplication. Or would you rather have me copy some more information from there?

**Review by razvand — APPROVED** [review]
Thanks, @mkroening 

Reviewed-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>
Approved-by: Razvan Deaconescu <razvan.deaconescu@cs.pub.ro>

**Comment by mkroening** [comment]
@razvand, what is needed to get this merged?

**Comment by nderjung** [comment]
Hi,

To get this merged, we must first merge the changes of the `lyon-hackathon` branch into `staging`.

**Comment by mkroening** [comment]
Could we merge this into `lyon-hackathon` to be done with this PR?

**Review by skuenzer — CHANGES_REQUESTED** [review]
Hi @mkroening, thanks a lot for this PR. I think most of it is introduced with PR #7, however, you could change this PR to add your description about "Duplicate symbols" to PR #7. What do you think?

**Comment by mkroening** [comment]
I opened https://github.com/skuenzer/app-elfloader/pull/1.

Closing in favor of your PR, @skuenzer. :)
